//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsoleClient.Menus {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ArchitectureResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArchitectureResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestConsoleClient.Menus.ArchitectureResource", typeof(ArchitectureResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   - {0}.
        /// </summary>
        internal static string ArchitectureNameDisplayItem {
            get {
                return ResourceManager.GetString("ArchitectureNameDisplayItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Asset.
        /// </summary>
        internal static string Asset_Suffix {
            get {
                return ResourceManager.GetString("Asset_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dispatcher1.
        /// </summary>
        internal static string Dispatcher1 {
            get {
                return ResourceManager.GetString("Dispatcher1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dispatcher2.
        /// </summary>
        internal static string Dispatcher2 {
            get {
                return ResourceManager.GetString("Dispatcher2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dispatcher3.
        /// </summary>
        internal static string Dispatcher3 {
            get {
                return ResourceManager.GetString("Dispatcher3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dispatcher4.
        /// </summary>
        internal static string Dispatcher4 {
            get {
                return ResourceManager.GetString("Dispatcher4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Product Name: .
        /// </summary>
        internal static string EnterProductNamePropmt {
            get {
                return ResourceManager.GetString("EnterProductNamePropmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to node1.
        /// </summary>
        internal static string Node1 {
            get {
                return ResourceManager.GetString("Node1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to node2.
        /// </summary>
        internal static string Node2 {
            get {
                return ResourceManager.GetString("Node2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to root.
        /// </summary>
        internal static string RootSystemName {
            get {
                return ResourceManager.GetString("RootSystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s1.
        /// </summary>
        internal static string System1 {
            get {
                return ResourceManager.GetString("System1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s1.1.
        /// </summary>
        internal static string System1_1 {
            get {
                return ResourceManager.GetString("System1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s1.2.
        /// </summary>
        internal static string System1_2 {
            get {
                return ResourceManager.GetString("System1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s1.2 dispatchable.
        /// </summary>
        internal static string System1_2Disp {
            get {
                return ResourceManager.GetString("System1_2Disp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s1.2 executable.
        /// </summary>
        internal static string System1_2Exec {
            get {
                return ResourceManager.GetString("System1_2Exec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s1.3.
        /// </summary>
        internal static string System1_3 {
            get {
                return ResourceManager.GetString("System1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s1.3.1.
        /// </summary>
        internal static string System1_3_1 {
            get {
                return ResourceManager.GetString("System1_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s1.3.2.
        /// </summary>
        internal static string System1_3_2 {
            get {
                return ResourceManager.GetString("System1_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s1.3 dispatchable.
        /// </summary>
        internal static string System1_3Disp {
            get {
                return ResourceManager.GetString("System1_3Disp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s1.3 executable1.
        /// </summary>
        internal static string System1_3Exec1 {
            get {
                return ResourceManager.GetString("System1_3Exec1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s1.3 executable2.
        /// </summary>
        internal static string System1_3Exec2 {
            get {
                return ResourceManager.GetString("System1_3Exec2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s2.
        /// </summary>
        internal static string System2 {
            get {
                return ResourceManager.GetString("System2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s2.1.
        /// </summary>
        internal static string System2_1 {
            get {
                return ResourceManager.GetString("System2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s2.1 dispatchable.
        /// </summary>
        internal static string System2_1Disp {
            get {
                return ResourceManager.GetString("System2_1Disp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s2.1 executable.
        /// </summary>
        internal static string System2_1Exec {
            get {
                return ResourceManager.GetString("System2_1Exec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s2.2.
        /// </summary>
        internal static string System2_2 {
            get {
                return ResourceManager.GetString("System2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s2.2 dispatchable.
        /// </summary>
        internal static string System2_2Disp {
            get {
                return ResourceManager.GetString("System2_2Disp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s2.2 executable.
        /// </summary>
        internal static string System2_2Exec {
            get {
                return ResourceManager.GetString("System2_2Exec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s2.3.
        /// </summary>
        internal static string System2_3 {
            get {
                return ResourceManager.GetString("System2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s2.3 dispatchable.
        /// </summary>
        internal static string System2_3Disp {
            get {
                return ResourceManager.GetString("System2_3Disp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s2.3 executable.
        /// </summary>
        internal static string System2_3Exec {
            get {
                return ResourceManager.GetString("System2_3Exec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s3.
        /// </summary>
        internal static string System3 {
            get {
                return ResourceManager.GetString("System3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s3.1.
        /// </summary>
        internal static string System3_1 {
            get {
                return ResourceManager.GetString("System3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s3.1.1.
        /// </summary>
        internal static string System3_1_1 {
            get {
                return ResourceManager.GetString("System3_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s3.1.1 dispatchable1.
        /// </summary>
        internal static string System3_1_1Disp1 {
            get {
                return ResourceManager.GetString("System3_1_1Disp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s3.1.1 dispatchable2.
        /// </summary>
        internal static string System3_1_1Disp2 {
            get {
                return ResourceManager.GetString("System3_1_1Disp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s3.1.1 dispatchable3.
        /// </summary>
        internal static string System3_1_1Disp3 {
            get {
                return ResourceManager.GetString("System3_1_1Disp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s3.1.1 executable.
        /// </summary>
        internal static string System3_1_1Exec {
            get {
                return ResourceManager.GetString("System3_1_1Exec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s3.1.2.
        /// </summary>
        internal static string System3_1_2 {
            get {
                return ResourceManager.GetString("System3_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s3.1.2 executable.
        /// </summary>
        internal static string System3_1_2Exec {
            get {
                return ResourceManager.GetString("System3_1_2Exec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s3.1.3.
        /// </summary>
        internal static string System3_1_3 {
            get {
                return ResourceManager.GetString("System3_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s3.1.3 executable.
        /// </summary>
        internal static string System3_1_3Exec {
            get {
                return ResourceManager.GetString("System3_1_3Exec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s3.2.
        /// </summary>
        internal static string System3_2 {
            get {
                return ResourceManager.GetString("System3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s3.3.
        /// </summary>
        internal static string System3_3 {
            get {
                return ResourceManager.GetString("System3_3", resourceCulture);
            }
        }
    }
}
